version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, backend]
    groups:
      go-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    labels: [dependencies]
